### ISSUE TITLE
Fix bug in unix-server mode: thread_pool was closed, but task is still not

### ISSUE THREAD

**Issue by p5-vbnekit** [p5-vbnekit/p5-python3-shelleport#1]
```
Task exception was never retrieved
future: <Task finished name='Task-9370' coro=<<async_generator_athrow without __name__>()> exception=AssertionError('not opened')>
Traceback (most recent call last):
  File "/home/user/src/p5/shelleport/_common/asynchronizer.py", line 36, in __aiter__
    try: yield await self.__executor(_next)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/src/p5/shelleport/_common/asynchronizer.py", line 39, in __aiter__
    finally: await self.__executor(_generator.close)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/p5/shelleport/_common/thread_pool.py", line 28, in __call__
    _executor = self.__manipulator.context
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/p5/shelleport/_common/context_manipulator.py", line 14, in context
    assert self.__manager is not None, "not opened"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: not opened
```

**Comment by p5-vbnekit** [comment]
It happens because top-level generator may not always finished completely after awaiting for `aclose`. For example, generator might be in state like this: `_data = await read(...)` before `yield _data`.

Protecting exported generators with a context manager (`_common.asynchronous_tools.generator_controller`) will fix it.
